/*TB_USER*/
CREATE TABLE TB_USER(
	USER_NO NUMBER ,
	USER_ID VARCHAR2(30) NOT NULL ,
	USER_PW VARCHAR2(30) NOT NULL ,
	USER_NAME VARCHAR2(30) NOT NULL ,
	ENROLL_DATE DATE DEFAULT SYSDATE ,
	
	CONSTRAINT TB_USER_PK PRIMARY KEY(USER_NO)
);
/*주석*/
COMMENT ON COLUMN TB_USER.USER_NO IS '사용자 번호';
COMMENT ON COLUMN TB_USER.USER_ID IS '사용자 아이디';
COMMENT ON COLUMN TB_USER.USER_PW IS '사용자 비밀번호';
COMMENT ON COLUMN TB_USER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN TB_USER.ENROLL_DATE IS '회원 가입일';

/*사용자 번호 생성용 시퀀스*/
CREATE SEQUENCE SEQ_USER_NO NOCACHE;

/*샘플 데이터 2개 삽입*/
INSERT INTO TB_USER VALUES(SEQ_USER_NO.NEXTVAL, 'user01','pass01','짱구',DEFAULT);
INSERT INTO TB_USER VALUES(SEQ_USER_NO.NEXTVAL, 'user02','pass02','훈이',DEFAULT);

COMMIT;

SELECT * FROM TB_USER;
SELECT * FROM EMPLOYEE;
SELECT * FROM KH_MEMBER;

--2025.03.12
--아이디, 비밀번호, 이름, 이메일, 가입일
CREATE TABLE KH_MEMBER(
	MEMBER_ID VARCHAR2(10) PRIMARY KEY ,
	MEMBER_PW VARCHAR2(20) NOT NULL ,
	MEMBER_NAME VARCHAR2(15) NOT NULL ,
	EMAIL VARCHAR2(50) ,
	ENROLL_DATE DATE DEFAULT SYSDATE	
);

CREATE SEQUENCE SEQ_KH_BOARD;

DROP TABLE KH_BOARD;
CREATE TABLE KH_BOARD(
	BOARD_NO NUMBER PRIMARY KEY,
	BOARD_CATEGORY VARCHAR2(20) NOT NULL,
	BOARD_WRITER VARCHAR2(10) REFERENCES KH_MEMBER,
	BOARD_TITLE VARCHAR2(300) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	COUNT NUMBER DEFAULT 0,
	CREATE_DATE DATE DEFAULT SYSDATE
);

SELECT * FROM KH_BOARD;
INSERT INTO KH_MEMBER VALUES('admin', 1234, '짱구', 'Wkdrn@kh.com', DEFAULT);
INSERT INTO KH_MEMBER VALUES('user01', 1234, '유리', 'dbfl@kh.com', DEFAULT);
INSERT INTO KH_MEMBER VALUES('user02', 1234, '맹구', 'aodrn@kh.com', DEFAULT);

ALTER TABLE KH_MEMBER MODIFY MEMBER_PW VARCHAR2(60);
UPDATE KH_MEMBER SET MEMBER_PW = '$2a$10$jpuf2OTXnK1t5vvTtvkOfOV9j31ufBnv7NQzuAybvJvVTT.14yiNS';

--게시글용 테이블 구현하기
--파일첨부기능 구현할 것 + 댓글기능 구현할 것
DROP TABLE TB_SPRING_BOARD;
CREATE TABLE TB_SPRING_BOARD(
	BOARD_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BOARD_TITLE VARCHAR2(200) NOT NULL,
	BOARD_CONTENT VARCHAR2(4000) NOT NULL,
	BOARD_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	COUNT NUMBER DEFAULT 0 NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
	CHANGE_NAME VARCHAR2(200),
	STATUS CHAR(1) DEFAULT 'Y' CHECK(STATUS IN ('Y','N'))
);
COMMIT;

INSERT INTO TB_SPRING_BOARD(BOARD_TITLE, BOARD_WRITER)
VALUES('첫 번째 글', 'admin');

SELECT * FROM TB_SPRING_BOARD;
SELECT * FROM TB_REPLY;

DROP TABLE TB_REPLY;
CREATE TABLE TB_REPLY(
	REPLY_NO NUMBER PRIMARY KEY,
	REPLY_WRITER VARCHAR2(10) NOT NULL REFERENCES KH_MEMBER,
	REPLY_CONTENT VARCHAR2(500) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	REF_BOARD_NO NUMBER NOT NULL REFERENCES TB_SPRING_BOARD
);

INSERT INTO TB_REPLY VALUES(SEQ_RNO.NEXTVAL, 'user01','히히모카', SYSDATE, 1);
INSERT INTO TB_REPLY VALUES(SEQ_RNO.NEXTVAL, 'user02','히히모카', SYSDATE, 2);

CREATE SEQUENCE SEQ_RNO;

--250328--------------------------------------------------
DROP TABLE TB_COMMENTS;
CREATE TABLE TB_COMMENTS(
	CONTENT VARCHAR2(1000) NOT NULL,
	CREATE_DATE DATE DEFAULT SYSDATE,
	UC_SEQ NUMBER NOT NULL
);
COMMIT;
SELECT * FROM TB_COMMENTS;
