SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_GRADE;

--1
SELECT STUDENT_NO AS"학번",STUDENT_NAME AS"이름",ENTRANCE_DATE AS"입학년도" 
FROM TB_STUDENT
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE ASC;

--2
SELECT PROFESSOR_NAME,PROFESSOR_SSN FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

--3
SELECT PROFESSOR_NAME AS "교수이름",2025-TO_NUMBER('19'||SUBSTR(PROFESSOR_SSN,1,2)) AS"나이"
FROM TB_PROFESSOR
WHERE PROFESSOR_SSN LIKE '%-1%' 
ORDER BY "나이" ASC, PROFESSOR_NAME ASC;

--4
SELECT SUBSTR(PROFESSOR_NAME,2) AS "이름" FROM TB_PROFESSOR;

--5
--SELECT STUDENT_NO,STUDENT_NAME FROM TB_STUDENT ;

--6
SELECT STUDENT_NO,STUDENT_NAME FROM TB_STUDENT 
WHERE STUDENT_NO NOT LIKE 'A%';

--7
SELECT ROUND(AVG(POINT),1) AS "평점" FROM TB_STUDENT s,TB_GRADE g
WHERE s.STUDENT_NO = g.STUDENT_NO AND S.STUDENT_NAME ='한아름';

--8
--SELECT DEPARTMENT_NO,COUNT() FROM TB_STUDENT;
--9
--10
--11
--12
--13

