SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;

--1
SELECT DEPARTMENT_NO "학과 명" ,CATEGORY "계열" FROM TB_DEPARTMENT;
--2
SELECT DEPARTMENT_NAME,CAPACITY AS "학과별 정원"
FROM TB_DEPARTMENT;
--3
SELECT STUDENT_NAME FROM TB_STUDENT 
WHERE DEPARTMENT_NO ='001' AND ABSENCE_YN ='Y' AND STUDENT_SSN LIKE '%-2%' ;
--
