SELECT * FROM TB_DEPARTMENT;
SELECT * FROM TB_STUDENT;
SELECT * FROM TB_PROFESSOR;
SELECT * FROM TB_CLASS;
SELECT * FROM TB_GRADE;

--1
SELECT STUDENT_NAME AS "학생 이름",STUDENT_ADDRESS AS "주소지" FROM TB_STUDENT
ORDER BY "학생 이름" ASC;

--2
SELECT STUDENT_NAME,STUDENT_SSN FROM TB_STUDENT;

--3

